### PR TITLE
Added name defaults

### LINKED ISSUE #114: Default names for transformers ; make all parameters keyword-only
`name` is the first parameter across all feature extractors, but it seems unnecessary in many situations. I propose that we should make it a default parameter and have it default to `self.__class__.__name__` or whatever, like how keras does it (and maybe do camel2snake case). Obviously this would require moving the argument position which would be a breaking change so I understand the hesitation to do anything about it. It's just messing with my global parameter filling a bit lol

### PR DESCRIPTION
**Pull request by beasteers**
Fixes #114

### CODE REVIEW

**Review by bmcfee — COMMENTED** [review]
LGTM.  Do you think we should apply the same changes to the Task hierarchy?

My thoughts:

- +: consistency with feature
- -: some tasks have default names already, but not all of them.  This was quasi-intentional.
- -: not all tasks have an obvious name (eg `VectorTransformer` or `StaticLabelTransformer`)
- -: breaks API because there are other required (positional) parameters, so making the first one have a default would require re-ordering.

**Comment by beasteers** [comment]
Hmm I mean like you said, most of them are already doing that. Yeah I guess the obvious name for those two could be the namespace? But there isn't really a way to avoid changing the API. The closest I think we could get without changing parameter order could be this:

```python
def __init__(self, name, namespace=None):
    namespace = namespace or name
```

But really that's backwards. This would make more sense:

```python
def __init__(self, namespace, *, name=None):
    name = name or namespace
```

But I think it could be okay leaving them as required for now

**Comment by bmcfee** [comment]
> But I think it could be okay leaving them as required for now

I agree.  Let's call this one done then?  (Thanks!)

**Comment by bmcfee** [comment]
I'm gonna hold off on merging this for a minute to see if it still makes sense to do a 0.5.1 release at all, or just push ahead to 0.6.0.

**Pull request merged**
